### PR TITLE
DenseNeuralNetwork

### PR DESCRIPTION
**Pull request by Mayank2184**
to predict Rg and Dmax

### CODE REVIEW

**Comment by kif** [comment]
Did you check your code ?
```

In [9]: import freesas.resources

In [10]: freesas.resources.resource_filename("keras_models/Rg+Dmax.keras")
Out[10]: '/home/kieffer/.venv/py311/lib/python3.11/site-packages/freesas/resources/keras_models/Rg+Dmax.keras'

In [11]: k=freesas.resources.resource_filename("keras_models/Rg+Dmax.keras")

In [12]: freesas.dnn.KerasDNN(k)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 freesas.dnn.KerasDNN(k)

File ~/.venv/py311/lib/python3.11/site-packages/freesas/dnn.py:154, in KerasDNN.__init__(self, keras_file)
    153 def __init__(self, keras_file):
--> 154     config, weights = parse_keras_file(keras_file)
    155     self.dnn =  DNN(*[DenseLayer(weights[2*i], weights[2*i+1], a) for i,a in enumerate(config[1])])

File ~/.venv/py311/lib/python3.11/site-packages/freesas/dnn.py:146, in parse_keras_file(keras_file)
    144 with zipfile.ZipFile(keras_file, 'r') as z:
    145     with z.open('config.json') as config_file:
--> 146         config = parse_config(config_file)
    147     with z.open('model.weights.h5') as weights_file:
    148         weights = load_weights(weights_file, config[0])

File ~/.venv/py311/lib/python3.11/site-packages/freesas/dnn.py:31, in parse_config(config_path)
     30 def parse_config(config_path):
---> 31     with open(config_path, 'r') as f:
     32         config = json.load(f)
     34     layer_dims = []

TypeError: expected str, bytes or os.PathLike object, not ZipExtFile
```

**Comment by Mayank2184** [comment]
Yes, I did it was working perfectly there.....

**Comment by kif** [comment]
It should almost be OK for the json part. I will have a look.

For the hdf5 side, I foresee some issues, on should probably go via `io.BytesIO` see:
https://docs.python.org/3/library/io.html

**Review by kif — APPROVED** [review]
LGTM

**Pull request merged**
